/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as ApiUnreadRouteImport } from './routes/api/unread'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiRefundRouteImport } from './routes/api/refund'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPayoutMethodsRouteImport } from './routes/api/payout-methods'
import { Route as ApiPaymentSettingsRouteImport } from './routes/api/payment-settings'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiCreatorsRouteImport } from './routes/api/creators'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedMeRouteImport } from './routes/_protected/me'
import { Route as ProtectedInboxRouteImport } from './routes/_protected/inbox'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCreatorsRouteImport } from './routes/_protected/creators'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ProtectedInboxIndexRouteImport } from './routes/_protected/inbox/index'
import { Route as ApiReleaseEscrowAccessIdRouteImport } from './routes/api/release-escrow.$accessId'
import { Route as ApiDmAccessUsernameRouteImport } from './routes/api/dm-access.$username'
import { Route as ApiCreatorsUsernameRouteImport } from './routes/api/creators.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedInboxUsernameRouteImport } from './routes/_protected/inbox/$username'
import { Route as ApiConversationsIdRefundRouteImport } from './routes/api/conversations.$id.refund'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations.$id.messages'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnreadRoute = ApiUnreadRouteImport.update({
  id: '/api/unread',
  path: '/api/unread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefundRoute = ApiRefundRouteImport.update({
  id: '/api/refund',
  path: '/api/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayoutMethodsRoute = ApiPayoutMethodsRouteImport.update({
  id: '/api/payout-methods',
  path: '/api/payout-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentSettingsRoute = ApiPaymentSettingsRouteImport.update({
  id: '/api/payment-settings',
  path: '/api/payment-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatorsRoute = ApiCreatorsRouteImport.update({
  id: '/api/creators',
  path: '/api/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMeRoute = ProtectedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInboxRoute = ProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreatorsRoute = ProtectedCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInboxIndexRoute = ProtectedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedInboxRoute,
} as any)
const ApiReleaseEscrowAccessIdRoute =
  ApiReleaseEscrowAccessIdRouteImport.update({
    id: '/api/release-escrow/$accessId',
    path: '/api/release-escrow/$accessId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDmAccessUsernameRoute = ApiDmAccessUsernameRouteImport.update({
  id: '/api/dm-access/$username',
  path: '/api/dm-access/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatorsUsernameRoute = ApiCreatorsUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ApiCreatorsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedInboxUsernameRoute = ProtectedInboxUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProtectedInboxRoute,
} as any)
const ApiConversationsIdRefundRoute =
  ApiConversationsIdRefundRouteImport.update({
    id: '/$id/refund',
    path: '/$id/refund',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof ProtectedAboutRoute
  '/creators': typeof ProtectedCreatorsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/inbox': typeof ProtectedInboxRouteWithChildren
  '/me': typeof ProtectedMeRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/payment-settings': typeof ApiPaymentSettingsRoute
  '/api/payout-methods': typeof ApiPayoutMethodsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/refund': typeof ApiRefundRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/inbox/$username': typeof ProtectedInboxUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/dm-access/$username': typeof ApiDmAccessUsernameRoute
  '/api/release-escrow/$accessId': typeof ApiReleaseEscrowAccessIdRoute
  '/inbox/': typeof ProtectedInboxIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof ProtectedAboutRoute
  '/creators': typeof ProtectedCreatorsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/me': typeof ProtectedMeRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/payment-settings': typeof ApiPaymentSettingsRoute
  '/api/payout-methods': typeof ApiPayoutMethodsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/refund': typeof ApiRefundRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/inbox/$username': typeof ProtectedInboxUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/dm-access/$username': typeof ApiDmAccessUsernameRoute
  '/api/release-escrow/$accessId': typeof ApiReleaseEscrowAccessIdRoute
  '/inbox': typeof ProtectedInboxIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/creators': typeof ProtectedCreatorsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/inbox': typeof ProtectedInboxRouteWithChildren
  '/_protected/me': typeof ProtectedMeRoute
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/payment-settings': typeof ApiPaymentSettingsRoute
  '/api/payout-methods': typeof ApiPayoutMethodsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/refund': typeof ApiRefundRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/inbox/$username': typeof ProtectedInboxUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/dm-access/$username': typeof ApiDmAccessUsernameRoute
  '/api/release-escrow/$accessId': typeof ApiReleaseEscrowAccessIdRoute
  '/_protected/inbox/': typeof ProtectedInboxIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/inbox'
    | '/me'
    | '/onboarding'
    | '/api/balance'
    | '/api/checkout'
    | '/api/conversations'
    | '/api/creators'
    | '/api/me'
    | '/api/payment-settings'
    | '/api/payout-methods'
    | '/api/ping'
    | '/api/refund'
    | '/api/stats'
    | '/api/unread'
    | '/api/webhook'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/inbox/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/dm-access/$username'
    | '/api/release-escrow/$accessId'
    | '/inbox/'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/me'
    | '/onboarding'
    | '/api/balance'
    | '/api/checkout'
    | '/api/conversations'
    | '/api/creators'
    | '/api/me'
    | '/api/payment-settings'
    | '/api/payout-methods'
    | '/api/ping'
    | '/api/refund'
    | '/api/stats'
    | '/api/unread'
    | '/api/webhook'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/inbox/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/dm-access/$username'
    | '/api/release-escrow/$accessId'
    | '/inbox'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/about'
    | '/_protected/creators'
    | '/_protected/dashboard'
    | '/_protected/inbox'
    | '/_protected/me'
    | '/_protected/onboarding'
    | '/api/balance'
    | '/api/checkout'
    | '/api/conversations'
    | '/api/creators'
    | '/api/me'
    | '/api/payment-settings'
    | '/api/payout-methods'
    | '/api/ping'
    | '/api/refund'
    | '/api/stats'
    | '/api/unread'
    | '/api/webhook'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/_protected/inbox/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/dm-access/$username'
    | '/api/release-escrow/$accessId'
    | '/_protected/inbox/'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiCreatorsRoute: typeof ApiCreatorsRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiPaymentSettingsRoute: typeof ApiPaymentSettingsRoute
  ApiPayoutMethodsRoute: typeof ApiPayoutMethodsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiRefundRoute: typeof ApiRefundRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUnreadRoute: typeof ApiUnreadRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDmAccessUsernameRoute: typeof ApiDmAccessUsernameRoute
  ApiReleaseEscrowAccessIdRoute: typeof ApiReleaseEscrowAccessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unread': {
      id: '/api/unread'
      path: '/api/unread'
      fullPath: '/api/unread'
      preLoaderRoute: typeof ApiUnreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refund': {
      id: '/api/refund'
      path: '/api/refund'
      fullPath: '/api/refund'
      preLoaderRoute: typeof ApiRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payout-methods': {
      id: '/api/payout-methods'
      path: '/api/payout-methods'
      fullPath: '/api/payout-methods'
      preLoaderRoute: typeof ApiPayoutMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-settings': {
      id: '/api/payment-settings'
      path: '/api/payment-settings'
      fullPath: '/api/payment-settings'
      preLoaderRoute: typeof ApiPaymentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creators': {
      id: '/api/creators'
      path: '/api/creators'
      fullPath: '/api/creators'
      preLoaderRoute: typeof ApiCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/me': {
      id: '/_protected/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ProtectedMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox': {
      id: '/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ProtectedInboxRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/creators': {
      id: '/_protected/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof ProtectedCreatorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox/': {
      id: '/_protected/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof ProtectedInboxIndexRouteImport
      parentRoute: typeof ProtectedInboxRoute
    }
    '/api/release-escrow/$accessId': {
      id: '/api/release-escrow/$accessId'
      path: '/api/release-escrow/$accessId'
      fullPath: '/api/release-escrow/$accessId'
      preLoaderRoute: typeof ApiReleaseEscrowAccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dm-access/$username': {
      id: '/api/dm-access/$username'
      path: '/api/dm-access/$username'
      fullPath: '/api/dm-access/$username'
      preLoaderRoute: typeof ApiDmAccessUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creators/$username': {
      id: '/api/creators/$username'
      path: '/$username'
      fullPath: '/api/creators/$username'
      preLoaderRoute: typeof ApiCreatorsUsernameRouteImport
      parentRoute: typeof ApiCreatorsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/inbox/$username': {
      id: '/_protected/inbox/$username'
      path: '/$username'
      fullPath: '/inbox/$username'
      preLoaderRoute: typeof ProtectedInboxUsernameRouteImport
      parentRoute: typeof ProtectedInboxRoute
    }
    '/api/conversations/$id/refund': {
      id: '/api/conversations/$id/refund'
      path: '/$id/refund'
      fullPath: '/api/conversations/$id/refund'
      preLoaderRoute: typeof ApiConversationsIdRefundRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
  }
}

interface ProtectedInboxRouteChildren {
  ProtectedInboxUsernameRoute: typeof ProtectedInboxUsernameRoute
  ProtectedInboxIndexRoute: typeof ProtectedInboxIndexRoute
}

const ProtectedInboxRouteChildren: ProtectedInboxRouteChildren = {
  ProtectedInboxUsernameRoute: ProtectedInboxUsernameRoute,
  ProtectedInboxIndexRoute: ProtectedInboxIndexRoute,
}

const ProtectedInboxRouteWithChildren = ProtectedInboxRoute._addFileChildren(
  ProtectedInboxRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedCreatorsRoute: typeof ProtectedCreatorsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedInboxRoute: typeof ProtectedInboxRouteWithChildren
  ProtectedMeRoute: typeof ProtectedMeRoute
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedCreatorsRoute: ProtectedCreatorsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedInboxRoute: ProtectedInboxRouteWithChildren,
  ProtectedMeRoute: ProtectedMeRoute,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiConversationsRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  ApiConversationsIdRefundRoute: typeof ApiConversationsIdRefundRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  ApiConversationsIdRefundRoute: ApiConversationsIdRefundRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiCreatorsRouteChildren {
  ApiCreatorsUsernameRoute: typeof ApiCreatorsUsernameRoute
}

const ApiCreatorsRouteChildren: ApiCreatorsRouteChildren = {
  ApiCreatorsUsernameRoute: ApiCreatorsUsernameRoute,
}

const ApiCreatorsRouteWithChildren = ApiCreatorsRoute._addFileChildren(
  ApiCreatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiCreatorsRoute: ApiCreatorsRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiPaymentSettingsRoute: ApiPaymentSettingsRoute,
  ApiPayoutMethodsRoute: ApiPayoutMethodsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiRefundRoute: ApiRefundRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiUnreadRoute: ApiUnreadRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDmAccessUsernameRoute: ApiDmAccessUsernameRoute,
  ApiReleaseEscrowAccessIdRoute: ApiReleaseEscrowAccessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
